### ISSUE TITLE
Don't need /data or /media volumes but /torrent blackhole is

### ISSUE THREAD

**Issue by fryfrog** [binhex/arch-nzbhydra2#1]
With configs living in `/config`, the `/data` and `/media` volumes aren't necessary. On the other hand, there is a torrent blackhole that should point at... well, the torrent daemon's blackhole directory. Maybe call it `/torrent-blackhole` so it doesn't get confused w/ an actual torrents download dir like `/torrents` in other dockers. Maybe? :/

**Comment by fryfrog** [comment]
I cloned this project in hopes of maybe sending a pull request, but I forgot how deeply nested your dockers are and I'm not sure I can easily replicate your build environment. :)

**Comment by binhex** [comment]
ive standardised on /data for any data generated by the application, such as torrent files, nzb files etc, and as this application can generate such files for passing through to blackhole im probably going to leave it as is.

/media im cool with removing, does nzbhydra2 do no checks for existing tv shows/movies etc?, no checks for any existing media of any kind?

**Comment by fryfrog** [comment]
Ah, sounds good for `/data`.

Yeah, nzbhydra(2) is just a proxy for indexers. It does nothing with media.

**Comment by weirdcrap** [comment]
I was curious about these, wasn't sure if I could remove them.

So if I don't ever plan on utilizing torrent blackhole functionality I potentially don't need either /data or /media mapped on the docker?

**Comment by fryfrog** [comment]
Yeah, but I'm not sure what happens if you don't feed in something for an expected volume. I'd feed something empty in for now, wait for @binhex to remove the unneeded stuff later.

**Comment by binhex** [comment]
@weirdcrap you can safely remove /data and /media, the only mandatory volume mapping is /config.

**Comment by binhex** [comment]
/media has now been removed from template, readme and dockerfile.

please note you may not see the change in the readme until the docker image is rebuilt (docker hub limitation)
