### ISSUE TITLE
Update to JDK 17

### ISSUE THREAD

**Issue by theotherp** [binhex/arch-nzbhydra2#16]
I'm planning to require JDK 17 at some point but it's already supported. Could you please release a prerelease / beta image using JDK 17 to prepare for that?

**Comment by binhex** [comment]
hi @theotherp i have switched it over to jre 17 openjdk and an image has just been built, im assuming jre is sufficient? (mot building from source).

**Comment by theotherp** [comment]
That's fine, thank you.

**Comment by binhex** [comment]
Excellent thanks for the confirmation I'm closing this off
