### ISSUE TITLE
Upgrade to Java 9 or 10

### ISSUE THREAD

**Issue by theotherp** [binhex/arch-nzbhydra2#2]
Hi,

I'm currently working on a new version which will allow to be run with Java 9 or 10. This would require a change in the container. How do we proceed for the switch to be as smoothly as possible?

Cheers.

**Comment by binhex** [comment]
The easiest way to do it would be for me to make the code change to ref Java 10 and then next release from you would trigger a build with that code change in, sound ok?

**Comment by theotherp** [comment]
Sounds good. I'll let you know.

**Comment by binhex** [comment]
Ok cool, just keep in mind I'm on holiday for two weeks from Sunday and internet connectivity will be very patch at best, so probably best to do it any time after that 😁

**Comment by theotherp** [comment]
Right.

**Comment by theotherp** [comment]
Alright, you're good to go. For now I recommend using Java 10. The current release works with Java 8-10.
