### ISSUE TITLE
2.2.0 is out

### ISSUE THREAD

**Issue by halkeye** [binhex/arch-nzbhydra2#4]
I don't think its a huge important change, but I get the warning every time i load the page.

**Comment by binhex** [comment]
i would expect there is an option to turn off notifications no?, in any case it's fully automated from my end, so as soon as a the release gets punted to Arch User Repository (AUR for short) then there will be an auto triggered build of the image, so dont worry it will happen.

edit - just checked and 2.2.0 has already been built, so just pull down the latest image.
