### ISSUE TITLE
Use OpenJDK J9

### ISSUE THREAD

**Issue by theotherp** [binhex/arch-nzbhydra2#5]
A while ago I updated my own container to use a different JVM which reduces memory usage. I haven't heard of any problems and haven't encountered any myself. If possible you could use that in your container. See https://github.com/theotherp/nzbhydra2/blob/master/misc/docker/Dockerfile

**Comment by binhex** [comment]
Thanks I will take a look

**Comment by fryfrog** [comment]
I *just* switched my native install to using `jre-openjdk` on Arch which is 11 and seems fine so far. Is there any special reason for 9 specifically? I peaked into binhex's container as part of deciding what to run and it was using 10.

**Comment by theotherp** [comment]
It's actually Java 8. The JVM implementation is called J9. See [here](https://adoptopenjdk.net/). Java 11 with J9 should also work.

J9 is the key component to reduce memory usage.

**Comment by fryfrog** [comment]
I installed and switched to `aur/jdk11-openj9-bin`, when stopped it was at ~550MB and when started on J9 it is at ~250MB. I *think* the original started up around 450MB last time. Will keep an eye on it.

**Comment by binhex** [comment]
hows it looking @fryfrog worth moving over to?

**Comment by fryfrog** [comment]
I'm at ~490MB usage after running overnight, so it doesn't appear to have made a big difference to me. I'll continue to run it, but maybe I should try the 9 or 10 J9 version?

**Comment by theotherp** [comment]
Too bad :-/

**Comment by binhex** [comment]
> but maybe I should try the 9 or 10 J9 version?

yeah go for it fryfrog!, im a bit busy with other stuff at the mo, so appreciate you doing the leg work.

**Comment by fryfrog** [comment]
There is something weird w/ the jdk9 j9 AUR package, so I'm running the jdk10. I'm 30 minutes in and at ~350MB, so not bad.

**Comment by fryfrog** [comment]
4 hours into `aur/jdk10-openjdk-openj9-bin` and I'm at 450MB.

**Comment by binhex** [comment]
ok i dont think its worth going any further with this guys, lets stick with what we have in place for now eh, closing off.
