### ISSUE TITLE
2.20.1 didn't seem to be built

### ISSUE THREAD

**Issue by halkeye** [binhex/arch-nzbhydra2#9]
https://hub.docker.com/r/binhex/arch-nzbhydra2/builds

Is this something that gets triggered externally? or is it supposed to auto build?

**Comment by binhex** [comment]
triggered by AUR:-
https://aur.archlinux.org/packages/nzbhydra2/

when that is updated the image will be automatically built.

**Comment by halkeye** [comment]
okay my bad then, I thought based on #8 you had a build script somewhere and it broke. I will be patient thanks
